version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pragmia-postgres
    environment:
      POSTGRES_DB:       pragmia
      POSTGRES_USER:     pragmia
      POSTGRES_PASSWORD: pragmia_secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pragmia"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pragmia-redis
    command: redis-server --requirepass redis_secret
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secret", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
