package io.pragmia.api.audit;

public enum AuditEventType {
    AUTH_SUCCESS, AUTH_FAILURE, AUTH_MFA_SUCCESS, AUTH_MFA_FAILURE, AUTH_LOCKED,
    SESSION_CREATED, SESSION_DESTROYED, SESSION_EXPIRED, SESSION_KILLED_BY_ADMIN, SESSION_KILL_BULK,
    TOKEN_ISSUED, TOKEN_REVOKED, TOKEN_INTROSPECTED,
    POLICY_EVALUATED_PERMIT, POLICY_EVALUATED_DENY, POLICY_CREATED, POLICY_UPDATED, POLICY_DELETED,
    ADMIN_USER_CREATED, ADMIN_USER_UPDATED, ADMIN_USER_DISABLED, ADMIN_CLIENT_REGISTERED, ADMIN_FLOW_UPDATED,
    NLP_COMMAND_RECEIVED, NLP_DUAL_APPROVAL_REQUESTED, NLP_DUAL_APPROVAL_GRANTED,
    NLP_DUAL_APPROVAL_DENIED, NLP_COMMAND_EXECUTED,
    SYSTEM_STARTUP, MODULE_ENABLED, MODULE_DISABLED
}
